/*
 * vistaFacturacion.java
 *
 * Created on 28 de mayo de 2008, 1:15
 */

package vistes;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  rael
 */
public class VistaFacturacio extends javax.swing.JPanel {


    private static String[] CabeceraListaFacturas = {"Data Facturació", "Import"};
    private static String[] CabeceraListaDesglose = {"Nom Programa", "Data Emissió", "Preu"};
    

    /*
     * Creates new form vistaExploradorFactures 
     */
    
    public VistaFacturacio() {
        initComponents();
    }

    public void aviso(String inmsg) {
        JOptionPane.showMessageDialog(null, (Object) inmsg);
    }

    /**
     * 
     * @param index 
     */
    
    public void seleccionarFactura(int index){
        lsFacturas.setRowSelectionInterval(index, 0);
    }
    
    public void setListaFacturas(Object[][] inDatos) {
        ((DefaultTableModel) (lsFacturas.getModel())).setDataVector(inDatos, CabeceraListaFacturas);
        lsFacturas.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    }

    public void setListaDesglose(Object[][] inDatos) {
        ((DefaultTableModel) (lsDesglose.getModel())).setDataVector(inDatos, CabeceraListaDesglose);
        lsDesglose.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setFechaFactura(String inFechaFactura){
        this.etDataFactura.setText(inFechaFactura);
    }
    
    public void setTotal(String inTotal){
        this.tbTotal.setText(inTotal);
    }
         
    
    
    public void setAction(ListSelectionListener lista, ActionListener[] acciones) {
        lsFacturas.getSelectionModel().addListSelectionListener(lista);
        bNovaFactura.addActionListener(acciones[0]);
    }
        
    
    public int getIndexFactura(){
        
        if (lsFacturas.getSelectedRowCount() == 1) {
            return lsFacturas.getSelectedRow();
        }
        
        return -1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lsFacturas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsDesglose = new javax.swing.JTable();
        etTitolFactura1 = new javax.swing.JLabel();
        etTituloDataFactura = new javax.swing.JLabel();
        etDataFactura = new javax.swing.JLabel();
        etTotal = new javax.swing.JLabel();
        tbTotal = new javax.swing.JTextField();
        bNovaFactura = new javax.swing.JButton();
        etEuro = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lsFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Data Factura", "Import"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsFacturas.setName("lsFacturas"); // NOI18N
        jScrollPane2.setViewportView(lsFacturas);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        lsDesglose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nom Programa", "Data Emissió", "Preu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsDesglose.setName("lsDesglose"); // NOI18N
        jScrollPane3.setViewportView(lsDesglose);

        etTitolFactura1.setFont(new java.awt.Font("Lucida Grande 18 18 18", 1, 18)); // NOI18N
        etTitolFactura1.setText("Factura"); // NOI18N
        etTitolFactura1.setName("etTitolFactura1"); // NOI18N

        etTituloDataFactura.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        etTituloDataFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etTituloDataFactura.setName("etTituloDataFactura"); // NOI18N

        etDataFactura.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        etDataFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etDataFactura.setName("etDataFactura"); // NOI18N

        etTotal.setFont(new java.awt.Font("Lucida Grande 16 12 12", 0, 12)); // NOI18N
        etTotal.setText("Import Total"); // NOI18N
        etTotal.setName("etTotal"); // NOI18N

        tbTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tbTotal.setName("tbTotal"); // NOI18N

        bNovaFactura.setText("Nova Factura"); // NOI18N
        bNovaFactura.setName("bNovaFactura"); // NOI18N

        etEuro.setFont(new java.awt.Font("Lucida Grande 16 12 12", 1, 14)); // NOI18N
        etEuro.setText("€"); // NOI18N
        etEuro.setName("etEuro"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 402, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(etTitolFactura1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 181, Short.MAX_VALUE)
                        .add(bNovaFactura))
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(etTituloDataFactura)
                        .add(18, 18, 18)
                        .add(etDataFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(etTotal)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(tbTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(etEuro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(etTitolFactura1)
                            .add(bNovaFactura))
                        .add(11, 11, 11)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 405, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(etTituloDataFactura)
                            .add(etDataFactura)
                            .add(etTotal)
                            .add(tbTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(etEuro))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNovaFactura;
    private javax.swing.JLabel etDataFactura;
    private javax.swing.JLabel etEuro;
    private javax.swing.JLabel etTitolFactura1;
    private javax.swing.JLabel etTituloDataFactura;
    private javax.swing.JLabel etTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lsDesglose;
    private javax.swing.JTable lsFacturas;
    private javax.swing.JTextField tbTotal;
    // End of variables declaration//GEN-END:variables

}
