/*
 * vistaNovaFactura.java
 *
 * Created on 22 de mayo de 2008, 7:44
 */
package vistes;

import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  rael
 */
public class VistaNovaFactura extends javax.swing.JFrame {

    private static String[] CabeceraListaPendientes = {"ID", "Nom Programa", "Format", "Data Emissió", "Preu"};
    private static String[] CabeceraListaParaFacturar = {"ID", "Nom Programa", "Data Emissió", "Preu"};
    Object[][] listaParaFacturar;
    LinkedList<Integer> llistaSeleccionats;
    int i = 0;

    /** Creates new form vistaNovaFactura */
    public VistaNovaFactura() {
        initComponents();
        llistaSeleccionats = new LinkedList();
    }

    public void aviso(String inmsg) {
        JOptionPane.showMessageDialog(null, (Object) inmsg);
    }

// Consultoras
    public String getAutofacturaPreuMax() {
        return tbAutofacturaPreu.getText();
    }

    public Calendar getAutofacturaPeriodeInici() {
        Calendar c = Calendar.getInstance();
        c.setTime((Date) this.spPeriodoInicio.getValue());
        return c;
    }

    public Calendar getAutofacturaPeriodeFi() {
        Calendar c = Calendar.getInstance();
        c.setTime((Date) this.spPeriodoFin.getValue());
        return c;
    }

// Cosas de la vista
    public void setAction(ActionListener[] acciones, WindowListener ventana) {
        bAutofacturaPreu.addActionListener(acciones[0]);
        bAutofacturaPeriode.addActionListener(acciones[1]);
        bFacturar.addActionListener(acciones[2]);
    }

// Lista Pendientes //
    public void setListaPendientes(Object[][] inDatos) {

        ((DefaultTableModel) (lsProgramesPendents.getModel())).setDataVector(inDatos, CabeceraListaPendientes);
        lsProgramesPendents.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaParaFacturar = new Object[lsProgramesPendents.getRowCount()][4];
    }

    public String[] getSeleccionadoListaPendientes() {
        String[] e = new String[4];
        if (lsProgramesPendents.getSelectedRowCount() == 1) {
            e[0] = String.valueOf(lsProgramesPendents.getModel().getValueAt(lsProgramesPendents.getSelectedRow(), 0));
            e[1] = (String) lsProgramesPendents.getModel().getValueAt(lsProgramesPendents.getSelectedRow(), 1);
            e[2] = (String) lsProgramesPendents.getModel().getValueAt(lsProgramesPendents.getSelectedRow(), 3);
            e[3] = String.valueOf(lsProgramesPendents.getModel().getValueAt(lsProgramesPendents.getSelectedRow(), 4));
        }

        return e;
    }

    public int[] getListaParaFacturar() {
        int[] e = new int[llistaSeleccionats.size()];

        for (i = 0; i < llistaSeleccionats.size(); i++) {
            e[i] = llistaSeleccionats.get(i);
        }

        return e;
    }

    /**
     * 
     * Lista Seleccionados
     * @param inDatos 
     */
    public void setListaSeleccionados(Object[][] inDatos) {
        listaParaFacturar = new Object[inDatos.length][3];
        listaParaFacturar = inDatos;
        for(i=0;i<inDatos.length;i++){
            llistaSeleccionats.add(Integer.parseInt((String) inDatos[i][0]));
        }
        actualizarListaSeleccionados();
    }

    public void actualizarListaSeleccionados() {
        ((DefaultTableModel) (lsProgramesSeleccionats.getModel())).setDataVector(listaParaFacturar, CabeceraListaParaFacturar);
        lsProgramesSeleccionats.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etPagarPeriode = new javax.swing.JLabel();
        etPagarMaxim = new javax.swing.JLabel();
        etTitolSeleccioAutomatica = new javax.swing.JLabel();
        etTitolSeleccionManual = new javax.swing.JLabel();
        tbAutofacturaPreu = new javax.swing.JTextField();
        bAutofacturaPeriode = new javax.swing.JButton();
        bAutofacturaPreu = new javax.swing.JButton();
        bAfegirSeleccio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsProgramesPendents = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsProgramesSeleccionats = new javax.swing.JTable();
        etTitolFactura = new javax.swing.JLabel();
        bNetejarFactura = new javax.swing.JButton();
        etTotal = new javax.swing.JLabel();
        tbTotal = new javax.swing.JTextField();
        bFacturar = new javax.swing.JButton();
        spPeriodoInicio = new javax.swing.JSpinner();
        spPeriodoFin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        etPagarPeriode.setText("Període"); // NOI18N
        etPagarPeriode.setName("etPagarPeriode"); // NOI18N

        etPagarMaxim.setText("Màxim a pagar"); // NOI18N
        etPagarMaxim.setName("etPagarMaxim"); // NOI18N

        etTitolSeleccioAutomatica.setFont(new java.awt.Font("Lucida Grande 18", 1, 14));
        etTitolSeleccioAutomatica.setText("Selecció Automática"); // NOI18N
        etTitolSeleccioAutomatica.setName("etTitolSeleccioAutomatica"); // NOI18N

        etTitolSeleccionManual.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        etTitolSeleccionManual.setText("Selecció Manual"); // NOI18N
        etTitolSeleccionManual.setName("etTitolSeleccionManual"); // NOI18N

        tbAutofacturaPreu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tbAutofacturaPreu.setText("0"); // NOI18N
        tbAutofacturaPreu.setName("tbAutofacturaPreu"); // NOI18N

        bAutofacturaPeriode.setFont(new java.awt.Font("Lucida Grande 13", 0, 12));
        bAutofacturaPeriode.setText("AutoFactura"); // NOI18N
        bAutofacturaPeriode.setName("bAutofacturaPeriode"); // NOI18N

        bAutofacturaPreu.setFont(new java.awt.Font("Lucida Grande 13", 0, 12));
        bAutofacturaPreu.setText("AutoFactura"); // NOI18N
        bAutofacturaPreu.setName("bAutofacturaPreu"); // NOI18N

        bAfegirSeleccio.setText("Afegir a factura"); // NOI18N
        bAfegirSeleccio.setName("bAfegirSeleccio"); // NOI18N
        bAfegirSeleccio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAfegirSeleccioMouseClicked(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lsProgramesPendents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom Programa", "Format", "Data Emissió", "Preu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsProgramesPendents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        lsProgramesPendents.setName("lsProgramesPendents"); // NOI18N
        lsProgramesPendents.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(lsProgramesPendents);
        lsProgramesPendents.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lsProgramesPendents.getColumnModel().getColumn(0).setResizable(false);
        lsProgramesPendents.getColumnModel().getColumn(0).setPreferredWidth(25);
        lsProgramesPendents.getColumnModel().getColumn(1).setResizable(false);
        lsProgramesPendents.getColumnModel().getColumn(1).setPreferredWidth(200);
        lsProgramesPendents.getColumnModel().getColumn(2).setResizable(false);
        lsProgramesPendents.getColumnModel().getColumn(3).setResizable(false);
        lsProgramesPendents.getColumnModel().getColumn(3).setPreferredWidth(100);
        lsProgramesPendents.getColumnModel().getColumn(4).setResizable(false);
        lsProgramesPendents.getColumnModel().getColumn(4).setPreferredWidth(50);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lsProgramesSeleccionats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom Programa", "Data Emissió", "Preu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsProgramesSeleccionats.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        lsProgramesSeleccionats.setName("lsProgramesSeleccionats"); // NOI18N
        jScrollPane1.setViewportView(lsProgramesSeleccionats);
        lsProgramesSeleccionats.getColumnModel().getColumn(0).setResizable(false);
        lsProgramesSeleccionats.getColumnModel().getColumn(0).setPreferredWidth(25);
        lsProgramesSeleccionats.getColumnModel().getColumn(1).setResizable(false);
        lsProgramesSeleccionats.getColumnModel().getColumn(1).setPreferredWidth(200);
        lsProgramesSeleccionats.getColumnModel().getColumn(2).setResizable(false);
        lsProgramesSeleccionats.getColumnModel().getColumn(2).setPreferredWidth(100);
        lsProgramesSeleccionats.getColumnModel().getColumn(3).setResizable(false);
        lsProgramesSeleccionats.getColumnModel().getColumn(3).setPreferredWidth(40);

        etTitolFactura.setFont(new java.awt.Font("Lucida Grande 18", 1, 14));
        etTitolFactura.setName("etTitolFactura"); // NOI18N

        bNetejarFactura.setText("Buidar factura"); // NOI18N
        bNetejarFactura.setName("bNetejarFactura"); // NOI18N
        bNetejarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNetejarFacturaActionPerformed(evt);
            }
        });
        bNetejarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNetejarFacturaMouseClicked(evt);
            }
        });

        etTotal.setFont(new java.awt.Font("Lucida Grande 16", 0, 12));
        etTotal.setText("Total a pagar"); // NOI18N
        etTotal.setName("etTotal"); // NOI18N

        tbTotal.setFont(new java.awt.Font("Lucida Grande 16 12", 0, 12));
        tbTotal.setText("0"); // NOI18N
        tbTotal.setName("tbTotal"); // NOI18N

        bFacturar.setText("Facturar"); // NOI18N
        bFacturar.setName("bFacturar"); // NOI18N

        spPeriodoInicio.setModel(new javax.swing.SpinnerDateModel());
        spPeriodoInicio.setName("spPeriodoInicio"); // NOI18N

        spPeriodoFin.setModel(new javax.swing.SpinnerDateModel());
        spPeriodoFin.setName("spPeriodoFin"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(spPeriodoInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(tbAutofacturaPreu)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(bAutofacturaPreu))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(spPeriodoFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(bAutofacturaPeriode))))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(bAfegirSeleccio))
                            .add(etTitolSeleccioAutomatica, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(etPagarPeriode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(72, 72, 72))
                            .add(etPagarMaxim, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(etTitolSeleccionManual)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(etTotal)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tbTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 111, Short.MAX_VALUE)
                        .add(bFacturar))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, 0, 0, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(243, 243, 243)
                                .add(bNetejarFactura)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(etTitolFactura, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(etTitolFactura)
                            .add(etTitolSeleccioAutomatica))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(39, 39, 39)
                                .add(bAutofacturaPeriode))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(bAutofacturaPreu)
                                        .add(tbAutofacturaPreu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(etPagarMaxim))
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(etPagarPeriode)
                                    .add(spPeriodoInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(spPeriodoFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(etTitolSeleccionManual)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(bNetejarFactura)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bAfegirSeleccio)
                    .add(tbTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(etTotal)
                    .add(bFacturar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void bAfegirSeleccioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAfegirSeleccioMouseClicked
// TODO add your handling code here:
    String e[] = new String[4];
    e = getSeleccionadoListaPendientes();
    
    if (!(llistaSeleccionats.contains(Integer.parseInt(e[0])))) {
        llistaSeleccionats.add(Integer.parseInt(e[0]));
    
        listaParaFacturar[i][0] = e[0];
        listaParaFacturar[i][1] = e[1];
        listaParaFacturar[i][2] = e[2];
        listaParaFacturar[i][3] = e[3];
        i = i + 1;

        actualizarListaSeleccionados();
        tbTotal.setText(String.valueOf(Float.parseFloat(tbTotal.getText()) + Float.parseFloat(e[3])));
}//GEN-LAST:event_bAfegirSeleccioMouseClicked
}                                            

private void bNetejarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNetejarFacturaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bNetejarFacturaActionPerformed

private void bNetejarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNetejarFacturaMouseClicked
// TODO add your handling code here:
    llistaSeleccionats.clear();
    listaParaFacturar = new Object[lsProgramesPendents.getRowCount()][4];
    i = 0;
    this.tbTotal.setText("0");
    actualizarListaSeleccionados();
}//GEN-LAST:event_bNetejarFacturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VistaNovaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAfegirSeleccio;
    private javax.swing.JButton bAutofacturaPeriode;
    private javax.swing.JButton bAutofacturaPreu;
    private javax.swing.JButton bFacturar;
    private javax.swing.JButton bNetejarFactura;
    private javax.swing.JLabel etPagarMaxim;
    private javax.swing.JLabel etPagarPeriode;
    private javax.swing.JLabel etTitolFactura;
    private javax.swing.JLabel etTitolSeleccioAutomatica;
    private javax.swing.JLabel etTitolSeleccionManual;
    private javax.swing.JLabel etTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lsProgramesPendents;
    private javax.swing.JTable lsProgramesSeleccionats;
    private javax.swing.JSpinner spPeriodoFin;
    private javax.swing.JSpinner spPeriodoInicio;
    private javax.swing.JTextField tbAutofacturaPreu;
    private javax.swing.JTextField tbTotal;
    // End of variables declaration//GEN-END:variables
}
