/*
 * VistaSelectProgrames2.java
 *
 * Created on 30 de mayo de 2008, 2:10
 */
package vistes;

import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  superman
 */
public class VistaSelectProgrames extends javax.swing.JDialog {

    Vector<String> seleccionats;

    /** Creates new form VistaSelectProgrames2 */
    public VistaSelectProgrames(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        seleccionats = new Vector<String>();
    }

    /**Modificadores dels atributs de les llistes i cuadres de text*/
    public void setLlistaProgrames(String[] strProgrames) {
        llistaProgrames.setListData(strProgrames);
    }

    public void setLlistaFiltres(String[] llistaEFiltres) {
        /*Afegim "Tots"*/
        String[] llistaAux = new String[llistaEFiltres.length + 1];
        llistaAux[0] = "Tots";
        System.arraycopy(llistaEFiltres, 0, llistaAux, 1, llistaEFiltres.length);
        llistaFiltres.setListData(llistaAux);
    }

    public void clearFitxa() {
        fitxaPrograma.setText("");
    }

    public int getFClickedInt() {
        if (buttonFiltreFormat.isSelected()) {
            return 0;
        }
        if (buttonFiltreCategoria.isSelected()) {
            return 1;
        }
        if (buttonFiltreNom.isSelected()) {
            return 2;
        }
        if (buttonFiltreTematica.isSelected()) {
            return 3;
        }
        return -1;
    }

    public String getFClickedStr() {
        if (buttonFiltreFormat.isSelected()) {
            return "format";
        }
        if (buttonFiltreCategoria.isSelected()) {
            return "categoria";
        }
        if (buttonFiltreNom.isSelected()) {
            return "nom";
        }
        if (buttonFiltreTematica.isSelected()) {
            return "tematica";
        }
        return "";
    }

    public String getFiltreSelected(boolean esTematica) {
        String result;
        if (!esTematica) {
            String filtreSelected = String.valueOf(llistaFiltres.getSelectedIndex() - 1);
            if (filtreSelected == null) {
                return "";
            }
            return String.valueOf(llistaFiltres.getSelectedIndex() - 1);
        }

        result = (String) llistaFiltres.getSelectedValue();

        if (result == null) {
            return "";
        }

        return result;
    }

    public void setCuadreFitxa(String fitxa) {
        fitxaPrograma.setText(fitxa);
    }

    public String getProgramaSelected() {
        String programaSelected = (String) llistaProgrames.getSelectedValue();
        if (programaSelected == null) {
            return "";
        }
        return programaSelected;
    }

    public Vector<String> getLlistaSeleccionats() {
        return seleccionats;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        llistaFiltres = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        llistaProgrames = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        llistaSeleccionats = new javax.swing.JList();
        botoEliminar = new javax.swing.JButton();
        buttonAddPrograma = new javax.swing.JButton();
        botoGenerar = new javax.swing.JButton();
        botoCancelar = new javax.swing.JButton();
        buttonFiltreFormat = new javax.swing.JToggleButton();
        buttonFiltreCategoria = new javax.swing.JToggleButton();
        buttonFiltreTematica = new javax.swing.JToggleButton();
        buttonFiltreNom = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fitxaPrograma = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        llistaFiltres.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tots" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        }
    );
    llistaFiltres.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    llistaFiltres.setSelectedIndex(0);
    jScrollPane1.setViewportView(llistaFiltres);

    llistaProgrames.setModel(new javax.swing.AbstractListModel() {
        String[] strings = { "Llista no inicialitzada" };
        public int getSize() { return strings.length; }
        public Object getElementAt(int i) { return strings[i]; }
    });
    llistaProgrames.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane3.setViewportView(llistaProgrames);

    llistaSeleccionats.setModel(new javax.swing.AbstractListModel() {
        String[] strings = { "Cap" };
        public int getSize() { return strings.length; }
        public Object getElementAt(int i) { return strings[i]; }
    });
    llistaSeleccionats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane4.setViewportView(llistaSeleccionats);

    botoEliminar.setText("Eliminar");
    botoEliminar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botoEliminarActionPerformed(evt);
        }
    });

    buttonAddPrograma.setText("Afegir");
    buttonAddPrograma.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonAddProgramaActionPerformed(evt);
        }
    });

    botoGenerar.setText("GENERAR");

    botoCancelar.setText("CANCELAR");

    buttonFiltreFormat.setText("FORMAT");

    buttonFiltreCategoria.setText("CATEGORIA");

    buttonFiltreTematica.setText("TEMATICA");

    buttonFiltreNom.setText("CERCA PER NOM");

    fitxaPrograma.setColumns(1);
    fitxaPrograma.setEditable(false);
    fitxaPrograma.setRows(6);
    jScrollPane2.setViewportView(fitxaPrograma);

    jButton1.setText("Reset");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonFiltreFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFiltreNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFiltreTematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFiltreCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jScrollPane2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botoGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonAddPrograma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botoEliminar)))
            .addGap(39, 39, 39))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddPrograma)
                    .addGap(167, 167, 167)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jScrollPane2)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonFiltreFormat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonFiltreCategoria)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonFiltreTematica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonFiltreNom))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botoGenerar)
                                .addComponent(botoCancelar))
                            .addGap(25, 25, 25))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoEliminar)
                    .addComponent(jButton1)))
            .addGap(30, 30, 30))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    private void buttonAddProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProgramaActionPerformed
        seleccionats.add((String) llistaSeleccionats.getSelectedValue());
        llistaSeleccionats.setListData(seleccionats);
    }//GEN-LAST:event_buttonAddProgramaActionPerformed

    private void botoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEliminarActionPerformed
        seleccionats.remove((String) llistaSeleccionats.getSelectedValue());
        llistaSeleccionats.setListData(seleccionats);
    }//GEN-LAST:event_botoEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        seleccionats.clear();
        llistaSeleccionats.setListData(seleccionats);
    }//GEN-LAST:event_jButton1ActionPerformed

    void setListeners(ActionListener[] accions, ListSelectionListener selFiltres, ListSelectionListener selProgs) {
        /**Associem cada ActionListener als botons, i el listener de seleccio a les llistes*/
        buttonFiltreFormat.addActionListener(accions[0]);
        buttonFiltreCategoria.addActionListener(accions[1]);
        buttonFiltreNom.addActionListener(accions[2]);
        buttonFiltreTematica.addActionListener(accions[3]);

        botoGenerar.addActionListener(accions[4]);

        llistaFiltres.getSelectionModel().addListSelectionListener(selFiltres);
        llistaProgrames.getSelectionModel().addListSelectionListener(selProgs);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoCancelar;
    private javax.swing.JButton botoEliminar;
    private javax.swing.JButton botoGenerar;
    private javax.swing.JButton buttonAddPrograma;
    private javax.swing.JToggleButton buttonFiltreCategoria;
    private javax.swing.JToggleButton buttonFiltreFormat;
    private javax.swing.JToggleButton buttonFiltreNom;
    private javax.swing.JToggleButton buttonFiltreTematica;
    private javax.swing.JTextArea fitxaPrograma;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList llistaFiltres;
    private javax.swing.JList llistaProgrames;
    private javax.swing.JList llistaSeleccionats;
    // End of variables declaration//GEN-END:variables
}
