/*
 * vistaFacturacion.java
 *
 * @author Rael Garcia Arnés    47808932M
 */

package vistes;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  rael
 */
public class VistaFacturacio extends javax.swing.JPanel {


    private static String[] CabeceraListaFacturas = {"Data Facturació", "Import"};
    private static String[] CabeceraListaDesglose = {"Nom Programa", "Data Emissió", "Preu"};
    

    /*
     * Creates new form vistaExploradorFactures 
     */
    
    public VistaFacturacio() {
        initComponents();
    }

    public void aviso(String inmsg) {
        JOptionPane.showMessageDialog(null, (Object) inmsg);
    }

    /**
     * 
     * @param index 
     */
    
    public void seleccionarFactura(int index){
        lsFacturas.setRowSelectionInterval(index, 0);
    }
    
    public void setListaFacturas(Object[][] inDatos) {
        ((DefaultTableModel) (lsFacturas.getModel())).setDataVector(inDatos, CabeceraListaFacturas);
        lsFacturas.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public void setListaDesglose(Object[][] inDatos) {
        ((DefaultTableModel) (lsDesglose.getModel())).setDataVector(inDatos, CabeceraListaDesglose);
        lsDesglose.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setFechaFactura(String inFechaFactura){
        this.etDataFactura.setText(inFechaFactura);
    }
    
    public void setTotal(String inTotal){
        this.tbTotal.setText(inTotal);
    }
         
    
    
    public void setAction(ListSelectionListener lista, ActionListener accion) {
        lsFacturas.getSelectionModel().addListSelectionListener(lista);
        bNovaFactura.addActionListener(accion);
    }
        
    
    public int getIndexFactura(){
        
        if (lsFacturas.getSelectedRowCount() == 1) {
            return lsFacturas.getSelectedRow();
        }
        else if  (lsFacturas.getRowCount()>0){
            return 1;
        }
        
        return -1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lsFacturas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsDesglose = new javax.swing.JTable();
        etTitolFactura1 = new javax.swing.JLabel();
        etTituloDataFactura = new javax.swing.JLabel();
        etDataFactura = new javax.swing.JLabel();
        etTotal = new javax.swing.JLabel();
        tbTotal = new javax.swing.JTextField();
        bNovaFactura = new javax.swing.JButton();
        etEuro = new javax.swing.JLabel();
        bSync = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lsFacturas.setBackground(new java.awt.Color(254, 254, 254));
        lsFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Data Factura", "Import"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsFacturas.setGridColor(new java.awt.Color(254, 254, 254));
        lsFacturas.setInheritsPopupMenu(true);
        lsFacturas.setName("lsFacturas"); // NOI18N
        lsFacturas.setOpaque(false);
        jScrollPane2.setViewportView(lsFacturas);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        lsDesglose.setBackground(new java.awt.Color(254, 254, 254));
        lsDesglose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom Programa", "Data Emissió", "Preu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsDesglose.setGridColor(new java.awt.Color(254, 254, 254));
        lsDesglose.setName("lsDesglose"); // NOI18N
        jScrollPane3.setViewportView(lsDesglose);

        etTitolFactura1.setFont(new java.awt.Font("Lucida Grande 18 18 18", 1, 18));
        etTitolFactura1.setText("Factura"); // NOI18N
        etTitolFactura1.setName("etTitolFactura1"); // NOI18N

        etTituloDataFactura.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        etTituloDataFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etTituloDataFactura.setName("etTituloDataFactura"); // NOI18N

        etDataFactura.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        etDataFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etDataFactura.setName("etDataFactura"); // NOI18N

        etTotal.setFont(new java.awt.Font("Lucida Grande 16 12 12", 0, 12));
        etTotal.setText("Import Total"); // NOI18N
        etTotal.setName("etTotal"); // NOI18N

        tbTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tbTotal.setName("tbTotal"); // NOI18N

        bNovaFactura.setText("Nova Factura"); // NOI18N
        bNovaFactura.setName("bNovaFactura"); // NOI18N

        etEuro.setFont(new java.awt.Font("Lucida Grande 16 12 12", 1, 14));
        etEuro.setText("€"); // NOI18N
        etEuro.setName("etEuro"); // NOI18N

        bSync.setText("Sincronizar"); // NOI18N
        bSync.setName("bSync"); // NOI18N
        bSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSyncActionPerformed(evt);
            }
        });
	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(etTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(etEuro))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etTitolFactura1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSync)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bNovaFactura)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etTitolFactura1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bNovaFactura)
                                    .addComponent(bSync)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(etTotal)
                                .addComponent(tbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etEuro))))
                    .addContainerGap()))
        );    }// </editor-fold>//GEN-END:initComponents

private void bSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSyncActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bSyncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bNovaFactura;
    public javax.swing.JButton bSync;
    private javax.swing.JLabel etDataFactura;
    private javax.swing.JLabel etEuro;
    private javax.swing.JLabel etTitolFactura1;
    private javax.swing.JLabel etTituloDataFactura;
    private javax.swing.JLabel etTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lsDesglose;
    private javax.swing.JTable lsFacturas;
    private javax.swing.JTextField tbTotal;
    // End of variables declaration//GEN-END:variables

}
